### ISSUE TITLE
Test fail: use of undeclared crate or module `tracing`

### ISSUE THREAD

**Issue by srid** [leptos-rs/start-axum-0.6#14]
This happens when running `cargo test --profile release --package start-axum` from inside [the nix shell (using rust nightly)](https://github.com/leptos-rs/start-axum/compare/main...srid:nixify):

```
   Doc-tests start-axum
error[E0433]: failed to resolve: use of undeclared crate or module `tracing`
  --> src/error_template.rs:25:1
   |
25 | #[component]
   | ^^^^^^^^^^^^ use of undeclared crate or module `tracing`
   |
   = note: this error originates in the attribute macro `::leptos::leptos_dom::tracing::instrument` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `tracing`
```

<img width="677" alt="image" src="https://github.com/leptos-rs/start-axum/assets/3998/740a29fc-3744-41b4-9f5e-2af7bfd690b4">

**Comment by gbj** [comment]
This fails because `cargo test` tries to run tests with all features. `tracing` is enabled only for `ssr` mode in this template, to keep WASM binary sizes small. Running `cargo test --profile release --features=ssr --package start-axum` works fine.
