### ISSUE TITLE
`fileserv.rs` can be removed

### ISSUE THREAD

**Issue by srid** [leptos-rs/start-axum-0.6#15]
I believe this module can be removed entirely, and `main.rs` can instead use `fallback_service` in its place, a. la:

```rust
let client_dist = ServeDir::new(leptos_options.site_root.clone());
...
let app = Router::new()
  ...
  .fallback_service(client_dist)
```

In context: https://github.com/srid/leptos-fullstack/blob/0639b5909d61701c2bbdbb34fe831d574af06efe/src/server.rs#L17-L22

This will also (positively?) change the behaviour of the program as it will now cause 404, as one would expect, on missing requests (instead of [falling back to serving the app](https://github.com/leptos-rs/start-axum/blob/182477f366dc0b43b909a6a845958382afcab613/src/fileserv.rs#L23)).

**Comment by srid** [comment]
I discovered that the application error handler can be decoupled (from static file service) via `tower::service_fn`

https://github.com/srid/leptos-fullstack/commit/2e86d5072d7533ce1859c7bfda78cc9d9b396f40

**Comment by benwis** [comment]
To me, this looks like a sidegrade, but to each their own. I'd still like to present a unified Leptos rendered error page though, whether the error comes from inside Leptos or in AXum
