### ISSUE TITLE
Hydration failed in `ErrorTemplate`

### ISSUE THREAD

**Issue by wuxianucw** [leptos-rs/start-axum-0.6#18]
When some error occurs, SSR sends `ErrorTemplate` component while CSR always trys to render `App`. This leads to hydration bugs and you can see error messages like below in DevTools:

```
panicked at D:\data\cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos_dom-0.4.8\src\html.rs:1265:13:
assertion failed: `(left == right)`
  left: `"H1"`,
 right: `"LINK"`: SSR and CSR elements have the same hydration key but different node kinds. Check out the docs for information about this kind of hydration bug: https://leptos-rs.github.io/leptos/ssr/24_hydration_bugs.html
```

**Comment by gbj** [comment]
I'm not sure how to reproduce this issue. I'd welcome either a reproduction or a PR to fix the behavior.

**Comment by wuxianucw** [comment]
Sorry, it seems to have been fixed. Thanks for the reply.
