### ISSUE TITLE
`Rust-Analyzer` doesn't work inside a `cfg_if!` branch

### ISSUE THREAD

**Issue by AndyJado** [leptos-rs/start-axum-0.6#31]
Is it my editor config or is it a thing? can I do anything about it?

**Comment by gbj** [comment]
`cfg_if!` is not great for a few reasons like this and I'm planning to replace it in the templates in the next version. You can use a plain `#[cfg]` macro in many instances with better effects.

See this commit, for example
https://github.com/leptos-rs/start-axum/commit/cabaf49d6e7b9d5074ec4d0bb869b6adb93fb8cd
