### ISSUE TITLE
code is inactive due to #[cfg] directives: feature = "ssr" is disabled (inactive-code)

### ISSUE THREAD

**Issue by oiwn** [leptos-rs/start-axum-0.6#44]
What could be the way to actually activate certain features during development? Is it possible via local configuration?

I tried Helix/Neovim with rust analyser and in both got:

> code is inactive due to #[cfg] directives: feature = "ssr" is disabled

**Comment by gbj** [comment]
You should tell rust-analyzer to activate all features, or specifically to activate the `ssr` feature, in your rust analyzer config. Here's my nvim setup, for example:
```
local rt = require("rust-tools")
rt.setup({
	server = {
		settings = {
			["rust-analyzer"] = {
				-- ...
				-- activate all features of crates
				cargo = {
					allFeatures = true,
				},
			-- ...
```

**Comment by oiwn** [comment]
Thank you! also it's possible to add `default = ["ssr"]` to `[features]` in `Cargo.toml`
